import Head from "next/head";
import { ThemeChanger } from "./components/ThemeChange";
import  Event  from "./components/_events";
import  Donation  from "./components/_donations";

export default function Home() {
  let event = new Event();
  let donation = new Donation();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <div className="Event">
        <button onClick={event.createEvent}>- Create Event</button>
        <button onClick={event.deleteEvent}>- Delete Event</button>
        <button onClick={event.updateEvent}>- Update Event</button>
        <button onClick={donation.createDonation}>- Create Donation</button>
        <button onClick={donation.deleteDonation}>- Delete Donation</button>
        <button onClick={donation.updateDonation}>- Update Donation</button>
      </div>        
      </main>
    </>
  );
}
