import Head from "next/head";
import { ThemeChanger } from "../components/ThemeChange";
import useEthereumContext from "../hooks/ethereumContext";
import { EthereumContext } from "../hooks/ethereumContext";
import WalletConnectHandler from "@/components/wallet/WalletConnectHandler";
import WalletAddress from "../components/wallet/WalletAddress";

export default function Home() {
  const { walletConnected } = useEthereumContext() as EthereumContext;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {!walletConnected ? (
          <WalletConnectHandler />
        ) : (
          <>
            <WalletAddress /> <ThemeChanger />
          </>
        )}
      </main>
    </>
  );
}
