
import Head from "next/head";
import { ThemeChanger } from "@/components/ThemeChange";
import WalletAddress from "@/components/Wallet/WalletAddress";
import WalletConnectHandler from "@/components/Wallet/WalletConnectHandler";
import {useEthereumContext,EthereumContext, EthereumContextProvider} from "../hooks/ethereumContext"


export default function Home() {
  const { walletConnected } = useEthereumContext() as EthereumContext;
  
  return (
    <>
    
      <Head>
        <title>Safenet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        {!walletConnected ? (
          
          <WalletConnectHandler />
        ) : (
          <>
        
            <WalletAddress /> <ThemeChanger />
            <button type ="button">Create event</button>
            

          </>
        )}
      </main>
      
    </>
  );
}
